using System;
using System.Collections.Generic;
using CatlikeCoding.TextBox;
using UnityEngine;

// Key caps the game's icon font never had, borrowed from Ori's sequel and worked over to sit
// beside the ones it does have.
//
// That font is two objects and you need both. The generator is a list of character to prefab,
// and the <icon> style carries a BitmapFont whose entry per character is what the text layout
// leaves room for; a character missing from the font is swapped for the missing-glyph box
// before it ever reaches the renderer. Its ascii table has no room for fifty more caps, but
// `otherChars` is an empty array searched by id, so the caps live in the private use area and
// nobody has to ration letters.
public static class RandomizerKeyIcons {
    private class Cap {
        public Cap(string name, int x, int y, int width, int height) {
            Name = name;
            X = x;
            Y = y;
            Width = width;
            Height = height;
        }

        public readonly string Name;

        public readonly int X;

        public readonly int Y;

        public readonly int Width;

        public readonly int Height;

        public char Character;

        // what to put in a message to draw it, once it has one
        public string Icon;

        // room for it on a line, worked out against a cap the font already has
        public float Advance = 1f;
    }

    // Where each cap sits in key_caps.png. Generated by prior_notes/tools/keycaps.py, which
    // cuts them out of the sprite atlas by their own bounds rather than by a grid.
    private static readonly Cap[] Caps = {
        new Cap("Alpha0", 3, 3, 67, 59),
        new Cap("Alpha1", 72, 3, 68, 59),
        new Cap("Alpha2", 142, 3, 68, 59),
        new Cap("Alpha3", 213, 3, 67, 60),
        new Cap("Alpha4", 282, 3, 68, 60),
        new Cap("Alpha5", 352, 3, 68, 60),
        new Cap("Alpha6", 422, 3, 68, 60),
        new Cap("Alpha7", 493, 3, 68, 60),
        new Cap("Alpha8", 563, 3, 67, 59),
        new Cap("Alpha9", 3, 66, 67, 59),
        new Cap("Alt", 72, 66, 79, 60),
        new Cap("Asterisk", 153, 66, 67, 60),
        new Cap("BackQuote", 223, 66, 67, 59),
        new Cap("Backslash", 292, 66, 67, 59),
        new Cap("Backspace", 362, 66, 119, 60),
        new Cap("CapsLock", 484, 66, 119, 60),
        new Cap("Comma", 3, 129, 68, 59),
        new Cap("End", 73, 129, 68, 60),
        new Cap("Equals", 143, 129, 67, 59),
        new Cap("F1", 213, 129, 67, 60),
        new Cap("F10", 282, 129, 67, 59),
        new Cap("F11", 352, 129, 68, 59),
        new Cap("F12", 422, 129, 68, 60),
        new Cap("F2", 492, 129, 68, 60),
        new Cap("F3", 562, 129, 68, 60),
        new Cap("F4", 3, 192, 68, 60),
        new Cap("F5", 73, 192, 67, 59),
        new Cap("F6", 142, 192, 67, 60),
        new Cap("F7", 212, 192, 68, 60),
        new Cap("F8", 282, 192, 67, 59),
        new Cap("F9", 352, 192, 67, 59),
        new Cap("G", 421, 192, 68, 60),
        new Cap("H", 491, 192, 67, 60),
        new Cap("Home", 561, 192, 67, 60),
        new Cap("I", 3, 255, 68, 60),
        new Cap("Insert", 73, 255, 68, 60),
        new Cap("J", 143, 255, 68, 60),
        new Cap("KeypadPlus", 213, 255, 67, 59),
        new Cap("LeftBracket", 283, 255, 67, 60),
        new Cap("M", 352, 255, 67, 60),
        new Cap("Minus", 422, 255, 68, 59),
        new Cap("N", 492, 255, 67, 59),
        new Cap("O", 562, 255, 67, 59),
        new Cap("P", 3, 318, 68, 59),
        new Cap("PageDown", 73, 318, 68, 59),
        new Cap("PageUp", 143, 318, 67, 60),
        new Cap("Period", 213, 318, 68, 59),
        new Cap("Question", 283, 318, 67, 60),
        new Cap("Quote", 352, 318, 67, 60),
        new Cap("RightBracket", 422, 318, 68, 60),
        new Cap("Semicolon", 492, 318, 67, 59),
        new Cap("Slash", 562, 318, 68, 59),
        new Cap("T", 3, 381, 67, 59),
        new Cap("U", 72, 381, 67, 60),
        new Cap("Y", 142, 381, 68, 60)
    };

    // Caps whose name is not a KeyCode, or that stand for more than one.
    private static readonly string[][] Also = {
        new[] { "Alt", "LeftAlt", "RightAlt" },
        new[] { "Comma", "Less" },
        new[] { "Period", "Greater" },
        new[] { "Semicolon", "Colon" },
        new[] { "Quote", "DoubleQuote" },
        new[] { "Equals", "Plus" },
        new[] { "Minus", "Underscore" },
        new[] { "BackQuote", "Tilde" }
    };

    // The game keeps Alpha7 and Alpha8 as stand-ins for the movement keys rather than as the
    // digits, so those two stay as the game left them wherever it does the asking.
    private static readonly KeyCode[] Reserved = { KeyCode.Alpha7, KeyCode.Alpha8 };

    // What to write in a message to draw a key, or null for one we have no cap for. A rando
    // bind on one of the reserved keys means that key and asks literally; the game's own text
    // means the movement keys and does not.
    public static string Glyph(KeyCode key, bool literal = false) {
        Register();
        Cap cap;
        if (!keys.TryGetValue(key, out cap) || (!literal && Array.IndexOf(Reserved, key) >= 0)) {
            return null;
        }

        return cap.Icon;
    }

    public static bool Ready {
        get { return registered; }
    }

    // Cheap to call again, and called from everything that might be first: the material it
    // needs comes from a message screen that is not around at the very start.
    public static void Register() {
        if (registered || registering) {
            return;
        }

        // the cheap half of the question, because this is asked every frame until it lands
        var messages = Game.UI.MessageController;
        if (messages == null || messages.HintMessage == null) {
            return;
        }

        registering = true;
        try {
            var font = Font();
            var sheet = Sheet();
            if (font == null || sheet == null) {
                return;
            }

            var pixels = sheet.GetPixels32();
            for (var i = 0; i < Caps.Length; i++) {
                var cap = Caps[i];
                cap.Character = (char)(Private + i);
                cap.Icon = "<icon>" + cap.Character + "</>";
                var quad = Quad(cap, Slice(cap, pixels, sheet.width, sheet.height), font);
                if (quad == null) {
                    return;
                }

                font.Icons.Add(new TextBoxIconsFontGenerator.IconData {
                    Character = cap.Character.ToString(), Icon = quad, Width = cap.Advance
                });

                Learn(cap);
            }

            Space();
            registered = true;
        } finally {
            registering = false;
        }
    }

    // Which keys each cap answers for. A name that is a KeyCode is its own answer.
    private static void Learn(Cap cap) {
        var named = Named(cap.Name);
        if (named != KeyCode.None) {
            keys[named] = cap;
        }

        foreach (var also in Also) {
            if (also[0] != cap.Name) {
                continue;
            }

            for (var i = 1; i < also.Length; i++) {
                var other = Named(also[i]);
                if (other != KeyCode.None) {
                    keys[other] = cap;
                }
            }
        }
    }

    private static KeyCode Named(string name) {
        try {
            return (KeyCode)Enum.Parse(typeof(KeyCode), name, true);
        } catch (Exception) {
            return KeyCode.None;
        }
    }

    // One cap's own image, cut out of the sheet. The sheet was packed top down and Unity reads
    // textures bottom up, so the row is counted from the other end.
    private static Texture2D Slice(Cap cap, Color32[] pixels, int width, int height) {
        var cut = new Texture2D(cap.Width, cap.Height, TextureFormat.ARGB32, false);
        var taken = new Color32[cap.Width * cap.Height];
        for (var y = 0; y < cap.Height; y++) {
            var row = height - (cap.Y + cap.Height) + y;
            for (var x = 0; x < cap.Width; x++) {
                taken[y * cap.Width + x] = pixels[row * width + cap.X + x];
            }
        }

        cut.SetPixels32(taken);
        cut.Apply();
        return cut;
    }

    // Sized, layered and sorted off a cap the font already has, so a borrowed one lands where
    // the ones beside it land.
    private static GameObject Quad(Cap cap, Texture2D texture, TextBoxIconsFontGenerator font) {
        var tight = Painted(texture);
        Solidify(texture);
        var known = font.FindIcon(Sized);
        var shown = known == null ? null : known.Icon;
        var reference = shown == null ? null : shown.GetComponentInChildren<Renderer>(true);
        var quad = RandomizerQuad.BuildTextured("keyCap" + cap.Name, texture, reference);
        if (quad == null) {
            return null;
        }

        // What the game's own caps carry, and what keeps them in front of the plate the menu
        // draws behind its legend: the render queue comes from world z, recomputed at runtime.
        // Without it a borrowed cap sits under that plate and reads a third as bright.
        quad.AddComponent<UberShaderRuntimeRenderOrder>();
        var paint = quad.GetComponent<Renderer>();
        if (paint != null) {
            // The game's own caps are drawn softened rather than at full strength. Softened in
            // the colour and not in the alpha: over the near-black these are nearly always
            // drawn on, the alpha barely tells and the colour is the whole of it.
            paint.material.color = new Color(Softened, Softened, Softened, 1f);
        }

        // The cap the renderer clones is a root with the art hung off it: the root lands on the
        // text's own line and the art sits up and right of it, which is what puts a cap level
        // with the words beside it.
        var root = new GameObject(quad.name);
        quad.transform.parent = root.transform;
        Fit(quad, texture, reference, shown, cap, tight);

        // Parked under something switched off rather than switched off itself: the renderer
        // clones the cap as it finds it, and throws away any clone that arrives inactive.
        root.transform.parent = Parked();
        return root;
    }

    // Borrowed art carries its own margin, so the cap is measured by the pixels that are
    // actually painted and sized against a cap the font already has.
    private static void Fit(GameObject quad, Texture2D texture, Renderer reference, GameObject shown, Cap cap, Rect tight) {
        if (reference == null) {
            return;
        }

        // an inactive renderer has no bounds, so the known cap is woken for the measurement
        // and put straight back before anything draws
        var was = shown.activeSelf;
        shown.SetActive(true);
        var size = reference.bounds.size;
        var lift = reference.transform.localPosition;
        shown.SetActive(was);
        if (size.y < 0.0001f || tight.height < 0.0001f) {
            return;
        }

        var tall = size.y * Fits / tight.height;
        var wide = tall * texture.width / texture.height;
        quad.transform.localScale = new Vector3(wide, tall, 1f);
        // the painted part is not always in the middle of its own image
        quad.transform.localPosition = new Vector3(
            lift.x - (tight.center.x - 0.5f) * wide, lift.y - (tight.center.y - 0.5f) * tall, lift.z);
        // The room a cap takes on a line is its own width and then some: the game's art carries
        // that margin inside the sprite, where ours was cut to the cap itself, so caps of ours
        // sat touching each other where the game's do not.
        cap.Advance = Gap * tight.width * wide / Mathf.Max(0.0001f, size.x);
    }

    // Borrowed art is drawn to be added to a lit scene rather than laid over a dark one: the
    // cap itself is only half opaque, which over this menu reads a third as bright as one of
    // the game's own. Firming the alpha up puts it back where the eye expects it, and the
    // plate takes the light the game's own caps are painted with.
    private static void Solidify(Texture2D texture) {
        var pixels = texture.GetPixels32();
        for (var i = 0; i < pixels.Length; i++) {
            // the glow around the cap is taken separately: it is what the art adds to a lit
            // scene, and over a dark menu it mostly makes the cap look bigger than it is
            var firm = Mathf.RoundToInt(pixels[i].a * (pixels[i].a >= Faint ? Firm : Halo));
            pixels[i].a = (byte)(firm > 255 ? 255 : firm);

            // The game's caps are lit across the plate, brightest at the top right corner and
            // falling away to the bottom left; a borrowed one is a flat void. Measured off
            // their own plates, and weighted up because their top left sits brighter than
            // their bottom right.
            var grey = (pixels[i].r + pixels[i].g + pixels[i].b) / 3;
            if (grey < Plate && pixels[i].a >= Faint) {
                var across = (i % texture.width) / (float)texture.width;
                var up = (i / texture.width) / (float)texture.height;
                var fade = Dim + (Lit - Dim) * (Rise * up + (1f - Rise) * across);
                // Faded out as the pixel approaches the border or the lettering rather than
                // held off them: a hard edge leaves a dark outline around both.
                var room = 1f - grey / (float)Plate;
                var mottle = fade + Grit * (Mottle(i % texture.width, i / texture.width) - 0.5f);
                var lit = (byte)Mathf.Clamp(Mathf.RoundToInt(room * mottle), 0, 255);
                pixels[i].r = Lift(pixels[i].r, lit);
                pixels[i].g = Lift(pixels[i].g, lit);
                pixels[i].b = Lift(pixels[i].b, lit);
            }
        }

        texture.SetPixels32(pixels);
        texture.Apply();
    }

    private static byte Lift(byte channel, byte by) {
        return (byte)Mathf.Min(255, channel + by);
    }

    // Two sizes of blob rather than one, so the light on the plate has a little tooth to it.
    // The lattice is in texels, and a cap draws at about two thirds of its texture.
    private static float Mottle(int x, int y) {
        return 0.6f * Lattice(x, y, 3) + 0.4f * Lattice(x, y, 6);
    }

    private static float Lattice(int x, int y, int step) {
        var gx = x / (float)step;
        var gy = y / (float)step;
        var x0 = Mathf.FloorToInt(gx);
        var y0 = Mathf.FloorToInt(gy);
        var fx = gx - x0;
        var fy = gy - y0;
        fx = fx * fx * (3f - 2f * fx);
        fy = fy * fy * (3f - 2f * fy);
        return Mathf.Lerp(Mathf.Lerp(Speck(x0, y0), Speck(x0 + 1, y0), fx),
                          Mathf.Lerp(Speck(x0, y0 + 1), Speck(x0 + 1, y0 + 1), fx), fy);
    }

    private static float Speck(int x, int y) {
        var h = (uint)(x * 374761393 + y * 668265263);
        h = (h ^ (h >> 13)) * 1274126177u;
        return ((h ^ (h >> 16)) & 0xFFFF) / 65535f;
    }

    // The part of the image with the cap in it, as a fraction of the whole. Measured on what is
    // solid rather than on anything at all, so the glow around a cap does not count as cap.
    private static Rect Painted(Texture2D texture) {
        var pixels = texture.GetPixels32();
        int left = texture.width, right = -1, bottom = texture.height, top = -1;
        for (var y = 0; y < texture.height; y++) {
            for (var x = 0; x < texture.width; x++) {
                if (pixels[y * texture.width + x].a <= Faint) {
                    continue;
                }

                if (x < left) { left = x; }
                if (x > right) { right = x; }
                if (y < bottom) { bottom = y; }
                if (y > top) { top = y; }
            }
        }

        if (right < left || top < bottom) {
            return new Rect(0f, 0f, 1f, 1f);
        }

        return new Rect(left / (float)texture.width, bottom / (float)texture.height,
            (right - left + 1) / (float)texture.width, (top - bottom + 1) / (float)texture.height);
    }

    // The generator says which prefab a character draws; what decides whether the character is
    // drawn at all is the BitmapFont the <icon> style carries. Its `otherChars` is searched by
    // id, so it has to stay in order.
    private static void Space() {
        foreach (var collection in Resources.FindObjectsOfTypeAll<TextStyleCollection>()) {
            if (collection == null || collection.styles == null) {
                continue;
            }

            foreach (var style in collection.styles) {
                if (style == null || style.font == null || !(style.renderer is MoonIconRenderer)) {
                    continue;
                }

                Widen(style.font);
            }
        }
    }

    private static void Widen(BitmapFont font) {
        if (font.otherChars == null || widened.Contains(font)) {
            return;
        }

        widened.Add(font);
        var was = font.otherChars.Length;
        var chars = new BitmapFontChar[was + Caps.Length];
        Array.Copy(font.otherChars, chars, was);
        for (var i = 0; i < Caps.Length; i++) {
            // uv and width stay zero: the prefab draws the cap, the font only spaces it
            chars[was + i] = new BitmapFontChar {
                id = Caps[i].Character,
                advance = Caps[i].Advance,
                height = 0.01f,
                kerningIds = new int[0],
                kernings = new float[0]
            };
        }

        Array.Sort(chars, (a, b) => a.id.CompareTo(b.id));
        font.otherChars = chars;
    }

    private static Texture2D Sheet() {
        var bytes = RandomizerResources.ReadResource(Art);
        if (bytes == null) {
            return null;
        }

        var sheet = new Texture2D(0, 0);
        sheet.LoadImage(bytes);
        return sheet;
    }

    private static TextBoxIconsFontGenerator Font() {
        foreach (var renderer in Resources.FindObjectsOfTypeAll<MoonIconRenderer>()) {
            if (renderer != null && renderer.Icons != null) {
                return renderer.Icons;
            }
        }

        return null;
    }

    private static Transform Parked() {
        if (parked == null) {
            var holder = new GameObject("randomizerKeyCaps");
            UnityEngine.Object.DontDestroyOnLoad(holder);
            holder.SetActive(false);
            parked = holder.transform;
        }

        return parked;
    }

    private const string Art = "key_caps.png";

    // the font's own Enter, which is the cap ours sit next to most. Caps are not all one size
    // -- ESC's art is a fifth taller than this -- so the one every legend shows is the one to
    // match, and a borrowed cap carries less margin than the game's own art.
    private const char Sized = 'D';

    private const float Fits = 0.88f;

    // measured against the game's own caps, which are drawn at about this
    private const float Softened = 0.45f;

    // measured off a row of them: eighty pixels of line for a sixty-four pixel cap
    private const float Gap = 1.25f;

    // solid enough to be the cap rather than the glow around it
    private const byte Faint = 128;

    // measured: the borrowed caps sit near half opacity, the game's own are solid
    private const float Firm = 1.9f;

    private const float Halo = 0.45f;

    // anything darker than this is the plate rather than the border or the lettering, and
    // these are where the light on it falls to and rises to
    private const int Plate = 60;

    private const int Dim = 5;

    private const int Lit = 68;

    // how much of the fade is vertical rather than horizontal, and how much tooth it has
    private const float Rise = 0.62f;

    private const float Grit = 16f;

    // the private use area, where a font may keep anything it likes
    private const int Private = 0xE000;

    private static readonly Dictionary<KeyCode, Cap> keys = new Dictionary<KeyCode, Cap>();

    private static readonly List<BitmapFont> widened = new List<BitmapFont>();

    private static bool registered;

    private static bool registering;

    private static Transform parked;
}
