using System;
using System.Collections.Generic;
using CatlikeCoding.TextBox;
using UnityEngine;

// Key caps the icon font lacks, borrowed from Ori's sequel. Each needs an entry in the icon
// generator (its prefab) and in the <icon> style's BitmapFont (its spacing; without one it draws
// as the missing-glyph box). They live in the private use area.
public static class RandomizerKeyIcons {
    private class Cap {
        public Cap(string name, int x, int y, int width, int height, float trim = 0f) {
            Name = name;
            X = x;
            Y = y;
            Width = width;
            Height = height;
            Trim = trim;
        }

        public readonly string Name;

        public readonly int X;

        public readonly int Y;

        public readonly int Width;

        public readonly int Height;

        // taken off the advance; an empirical correction, only Backspace needs one
        public readonly float Trim;

        public char Character;

        // what to put in a message to draw it, once it has one
        public string Icon;

        // room for it on a line, worked out against a cap the font already has
        public float Advance = 1f;
    }

    // Where each cap sits in key_caps.png; generated by prior_notes/tools/keycaps.py.
    private static readonly Cap[] Caps = {
        new Cap("Alpha0", 3, 3, 67, 59),
        new Cap("Alpha1", 72, 3, 68, 59),
        new Cap("Alpha2", 142, 3, 68, 59),
        new Cap("Alpha3", 213, 3, 67, 60),
        new Cap("Alpha4", 282, 3, 68, 60),
        new Cap("Alpha5", 352, 3, 68, 60),
        new Cap("Alpha6", 422, 3, 68, 60),
        new Cap("Alpha7", 493, 3, 68, 60),
        new Cap("Alpha8", 563, 3, 67, 59),
        new Cap("Alpha9", 3, 66, 67, 59),
        new Cap("Alt", 72, 66, 79, 60),
        new Cap("Asterisk", 153, 66, 67, 60),
        new Cap("BackQuote", 223, 66, 67, 59),
        new Cap("Backslash", 292, 66, 67, 59),
        new Cap("Backspace", 362, 66, 119, 60, Wide),
        new Cap("CapsLock", 484, 66, 119, 60),
        new Cap("Comma", 3, 129, 68, 59),
        new Cap("End", 73, 129, 68, 60),
        new Cap("Equals", 143, 129, 67, 59),
        new Cap("F1", 213, 129, 67, 60),
        new Cap("F10", 282, 129, 67, 59),
        new Cap("F11", 352, 129, 68, 59),
        new Cap("F12", 422, 129, 68, 60),
        new Cap("F2", 492, 129, 68, 60),
        new Cap("F3", 562, 129, 68, 60),
        new Cap("F4", 3, 192, 68, 60),
        new Cap("F5", 73, 192, 67, 59),
        new Cap("F6", 142, 192, 67, 60),
        new Cap("F7", 212, 192, 68, 60),
        new Cap("F8", 282, 192, 67, 59),
        new Cap("F9", 352, 192, 67, 59),
        new Cap("G", 421, 192, 68, 60),
        new Cap("H", 491, 192, 67, 60),
        new Cap("Home", 561, 192, 67, 60),
        new Cap("I", 3, 255, 68, 60),
        new Cap("Insert", 73, 255, 68, 60),
        new Cap("J", 143, 255, 68, 60),
        new Cap("KeypadPlus", 213, 255, 67, 59),
        new Cap("LeftBracket", 283, 255, 67, 60),
        new Cap("M", 352, 255, 67, 60),
        new Cap("Minus", 422, 255, 68, 59),
        new Cap("N", 492, 255, 67, 59),
        new Cap("O", 562, 255, 67, 59),
        new Cap("P", 3, 318, 68, 59),
        new Cap("PageDown", 73, 318, 68, 59),
        new Cap("PageUp", 143, 318, 67, 60),
        new Cap("Period", 213, 318, 68, 59),
        new Cap("Question", 283, 318, 67, 60),
        new Cap("Quote", 352, 318, 67, 60),
        new Cap("RightBracket", 422, 318, 68, 60),
        new Cap("Semicolon", 492, 318, 67, 59),
        new Cap("Slash", 562, 318, 68, 59),
        new Cap("T", 3, 381, 67, 59),
        new Cap("U", 72, 381, 67, 60),
        new Cap("Y", 142, 381, 68, 60)
    };

    // Caps whose name is not a KeyCode, or that stand for more than one.
    private static readonly string[][] Also = {
        new[] { "Alt", "LeftAlt", "RightAlt" },
        new[] { "Comma", "Less" },
        new[] { "Period", "Greater" },
        new[] { "Semicolon", "Colon" },
        new[] { "Quote", "DoubleQuote" },
        new[] { "Equals", "Plus" },
        new[] { "Minus", "Underscore" },
        new[] { "BackQuote", "Tilde" }
    };

    // the game's text means the movement keys by these two, not the digits
    private static readonly KeyCode[] Reserved = { KeyCode.Alpha7, KeyCode.Alpha8 };

    // The <icon> text for a key, or null; only a literal ask (a rando bind) gets the Reserved two.
    public static string Glyph(KeyCode key, bool literal = false) {
        Register();
        Cap cap;
        if (!keys.TryGetValue(key, out cap) || (!literal && Array.IndexOf(Reserved, key) >= 0)) {
            return null;
        }

        return cap.Icon;
    }

    // Our cap first, asked literally so a digit is a digit; else the game's cap or the key's name.
    public static string Caption(KeyCode key) {
        return Glyph(key, true) ?? ButtonIconUtility.IconFor(key);
    }

    public static bool Ready {
        get { return registered; }
    }

    // Idempotent and all or nothing; retried until the hint message exists, never after a cap fails.
    public static void Register() {
        if (registered || registering || failed) {
            return;
        }

        // asked every frame until it lands, so the cheap test goes first
        var messages = Game.UI.MessageController;
        if (messages == null || messages.HintMessage == null) {
            return;
        }

        registering = true;
        try {
            var font = Font();
            if (font == null) {
                return;
            }

            var sheet = Sheet();
            if (sheet == null) {
                GiveUp("no " + Art);
                return;
            }

            var pixels = sheet.GetPixels32();
            var quads = new GameObject[Caps.Length];
            var cuts = new Texture2D[Caps.Length];
            for (var i = 0; i < Caps.Length; i++) {
                var cap = Caps[i];
                cap.Character = (char)(Private + i);
                cap.Icon = "<icon>" + cap.Character + "</>";
                cuts[i] = Slice(cap, pixels, sheet.width, sheet.height);
                quads[i] = Quad(cap, cuts[i], font);
                if (quads[i] == null) {
                    for (var j = 0; j < i; j++) {
                        UnityEngine.Object.Destroy(quads[j]);
                    }

                    for (var j = 0; j <= i; j++) {
                        UnityEngine.Object.Destroy(cuts[j]);
                    }

                    UnityEngine.Object.Destroy(sheet);
                    GiveUp("no quad for " + cap.Name);
                    return;
                }
            }

            UnityEngine.Object.Destroy(sheet);
            for (var i = 0; i < Caps.Length; i++) {
                font.Icons.Add(new TextBoxIconsFontGenerator.IconData {
                    Character = Caps[i].Character.ToString(), Icon = quads[i], Width = Caps[i].Advance
                });

                Learn(Caps[i]);
            }

            Blank(font);
            Space();
            registered = true;
        } finally {
            registering = false;
        }
    }

    private static void GiveUp(string why) {
        failed = true;
        Randomizer.log("key caps: " + why + "; using key names");
    }

    // Caps that draw nothing and only take width, since a run of spaces lays out as one: Gap
    // parts two hints, Thin follows a held hint's glyph to clear its ring.
    private static void Blank(TextBoxIconsFontGenerator font) {
        gap = Empty(font, 0, Pad);
        thin = Empty(font, 1, Clearance);
    }

    private static string Empty(TextBoxIconsFontGenerator font, int which, float width) {
        blanks[which] = (char)(Private + Caps.Length + which);
        // active under the parked holder: the renderer discards clones that arrive inactive
        var empty = new GameObject("keyCapBlank" + which);
        empty.transform.parent = Parked();
        font.Icons.Add(new TextBoxIconsFontGenerator.IconData {
            Character = blanks[which].ToString(), Icon = empty, Width = width
        });
        return "<icon>" + blanks[which] + "</>";
    }

    // What to write between two hints that share a legend slot.
    public static string Gap {
        get {
            Register();
            return gap;
        }
    }

    // What to write after the glyph of a hint that is held, to clear its ring.
    public static string Thin {
        get {
            Register();
            return thin;
        }
    }

    // Which keys each cap answers for. A name that is a KeyCode is its own answer.
    private static void Learn(Cap cap) {
        var named = Named(cap.Name);
        if (named != KeyCode.None) {
            keys[named] = cap;
        }

        foreach (var also in Also) {
            if (also[0] != cap.Name) {
                continue;
            }

            for (var i = 1; i < also.Length; i++) {
                var other = Named(also[i]);
                if (other != KeyCode.None) {
                    keys[other] = cap;
                }
            }
        }
    }

    private static KeyCode Named(string name) {
        try {
            return (KeyCode)Enum.Parse(typeof(KeyCode), name, true);
        } catch (Exception) {
            return KeyCode.None;
        }
    }

    // One cap cut out of the sheet, which is packed top down while Unity's rows run bottom up.
    private static Texture2D Slice(Cap cap, Color32[] pixels, int width, int height) {
        var cut = new Texture2D(cap.Width, cap.Height, TextureFormat.ARGB32, false);
        var taken = new Color32[cap.Width * cap.Height];
        for (var y = 0; y < cap.Height; y++) {
            var row = height - (cap.Y + cap.Height) + y;
            for (var x = 0; x < cap.Width; x++) {
                taken[y * cap.Width + x] = pixels[row * width + cap.X + x];
            }
        }

        cut.SetPixels32(taken);
        cut.Apply();
        return cut;
    }

    // Sized, layered and sorted off a cap the font already has.
    private static GameObject Quad(Cap cap, Texture2D texture, TextBoxIconsFontGenerator font) {
        var tight = Painted(texture);
        Solidify(texture);
        var known = font.FindIcon(Sized);
        var shown = known == null ? null : known.Icon;
        var reference = shown == null ? null : shown.GetComponentInChildren<Renderer>(true);
        var quad = RandomizerQuad.BuildTextured("keyCap" + cap.Name, texture, reference);
        if (quad == null) {
            return null;
        }

        // render queue from world z, as the game's caps have; without it this draws under the legend plate
        quad.AddComponent<UberShaderRuntimeRenderOrder>();
        var paint = quad.GetComponent<Renderer>();
        if (paint != null) {
            // softened like the game's caps, in the colour: over the dark plate alpha barely shows
            paint.material.color = new Color(Softened, Softened, Softened, 1f);
        }

        // like the game's caps: a root on the text line, the art offset up and right of it
        var root = new GameObject(quad.name);
        quad.transform.parent = root.transform;
        Fit(quad, texture, reference, shown, cap, tight);

        // under an inactive holder but active itself: the renderer discards inactive clones
        root.transform.parent = Parked();
        return root;
    }

    // Sized by its painted pixels against a known cap; the borrowed art carries extra margin.
    private static void Fit(GameObject quad, Texture2D texture, Renderer reference, GameObject shown, Cap cap, Rect tight) {
        if (reference == null) {
            return;
        }

        // an inactive renderer has no bounds: wake the known cap just for the measurement
        var was = shown.activeSelf;
        shown.SetActive(true);
        var size = reference.bounds.size;
        var lift = reference.transform.localPosition;
        shown.SetActive(was);
        if (size.y < 0.0001f || tight.height < 0.0001f) {
            return;
        }

        var tall = size.y * Fits / tight.height;
        var wide = tall * texture.width / texture.height;
        quad.transform.localScale = new Vector3(wide, tall, 1f);
        // the painted part is not always in the middle of its own image
        quad.transform.localPosition = new Vector3(
            lift.x - (tight.center.x - 0.5f) * wide, lift.y - (tight.center.y - 0.5f) * tall, lift.z);
        // painted width plus a fixed margin, which the game's sprites carry inside the art
        cap.Advance = tight.width * wide / Mathf.Max(0.0001f, size.x) + Margin - cap.Trim;
    }

    // The sequel's caps are half-opaque art for a lit scene: firm the alpha, damp the glow, and
    // light the plate the way the game's own caps are lit.
    private static void Solidify(Texture2D texture) {
        var pixels = texture.GetPixels32();
        for (var i = 0; i < pixels.Length; i++) {
            // the glow is damped, not firmed: over a dark menu it only makes the cap look bigger
            var firm = Mathf.RoundToInt(pixels[i].a * (pixels[i].a >= Faint ? Firm : Halo));
            pixels[i].a = (byte)(firm > 255 ? 255 : firm);

            // plate light: brightest top right, falling to bottom left, weighted vertical (Rise)
            var grey = (pixels[i].r + pixels[i].g + pixels[i].b) / 3;
            if (grey < Plate && pixels[i].a >= Faint) {
                var across = (i % texture.width) / (float)texture.width;
                var up = (i / texture.width) / (float)texture.height;
                var fade = Dim + (Lit - Dim) * (Rise * up + (1f - Rise) * across);
                // fades toward border and lettering; a hard cut-off would outline both in dark
                var room = 1f - grey / (float)Plate;
                var mottle = fade + Grit * (Mottle(i % texture.width, i / texture.width) - 0.5f);
                var lit = (byte)Mathf.Clamp(Mathf.RoundToInt(room * mottle), 0, 255);
                pixels[i].r = Lift(pixels[i].r, lit);
                pixels[i].g = Lift(pixels[i].g, lit);
                pixels[i].b = Lift(pixels[i].b, lit);
            }
        }

        texture.SetPixels32(pixels);
        texture.Apply();
    }

    private static byte Lift(byte channel, byte by) {
        return (byte)Mathf.Min(255, channel + by);
    }

    // value noise at two scales, in texels, to give the plate light a little tooth
    private static float Mottle(int x, int y) {
        return 0.6f * Lattice(x, y, 3) + 0.4f * Lattice(x, y, 6);
    }

    private static float Lattice(int x, int y, int step) {
        var gx = x / (float)step;
        var gy = y / (float)step;
        var x0 = Mathf.FloorToInt(gx);
        var y0 = Mathf.FloorToInt(gy);
        var fx = gx - x0;
        var fy = gy - y0;
        fx = fx * fx * (3f - 2f * fx);
        fy = fy * fy * (3f - 2f * fy);
        return Mathf.Lerp(Mathf.Lerp(Speck(x0, y0), Speck(x0 + 1, y0), fx),
                          Mathf.Lerp(Speck(x0, y0 + 1), Speck(x0 + 1, y0 + 1), fx), fy);
    }

    private static float Speck(int x, int y) {
        var h = (uint)(x * 374761393 + y * 668265263);
        h = (h ^ (h >> 13)) * 1274126177u;
        return ((h ^ (h >> 16)) & 0xFFFF) / 65535f;
    }

    // Bounds of the solid pixels as a fraction of the image; the glow does not count.
    private static Rect Painted(Texture2D texture) {
        var pixels = texture.GetPixels32();
        int left = texture.width, right = -1, bottom = texture.height, top = -1;
        for (var y = 0; y < texture.height; y++) {
            for (var x = 0; x < texture.width; x++) {
                if (pixels[y * texture.width + x].a <= Faint) {
                    continue;
                }

                if (x < left) { left = x; }
                if (x > right) { right = x; }
                if (y < bottom) { bottom = y; }
                if (y > top) { top = y; }
            }
        }

        if (right < left || top < bottom) {
            return new Rect(0f, 0f, 1f, 1f);
        }

        return new Rect(left / (float)texture.width, bottom / (float)texture.height,
            (right - left + 1) / (float)texture.width, (top - bottom + 1) / (float)texture.height);
    }

    // Adds the caps to every <icon> style's BitmapFont; `otherChars` is binary-searched, so sorted.
    private static void Space() {
        foreach (var collection in Resources.FindObjectsOfTypeAll<TextStyleCollection>()) {
            if (collection == null || collection.styles == null) {
                continue;
            }

            foreach (var style in collection.styles) {
                if (style == null || style.font == null || !(style.renderer is MoonIconRenderer)) {
                    continue;
                }

                Widen(style.font);
            }
        }
    }

    private static void Widen(BitmapFont font) {
        if (font.otherChars == null || widened.Contains(font)) {
            return;
        }

        widened.Add(font);
        var was = font.otherChars.Length;
        var chars = new BitmapFontChar[was + Caps.Length + blanks.Length];
        Array.Copy(font.otherChars, chars, was);
        for (var i = 0; i < Caps.Length; i++) {
            // uv and width stay zero: the prefab draws the cap, the font only spaces it
            chars[was + i] = new BitmapFontChar {
                id = Caps[i].Character,
                advance = Caps[i].Advance,
                height = 0.01f,
                kerningIds = new int[0],
                kernings = new float[0]
            };
        }

        var widths = new[] { Pad, Clearance };
        for (var i = 0; i < blanks.Length; i++) {
            chars[was + Caps.Length + i] = new BitmapFontChar {
                id = blanks[i],
                advance = widths[i],
                height = 0.01f,
                kerningIds = new int[0],
                kernings = new float[0]
            };
        }

        Array.Sort(chars, (a, b) => a.id.CompareTo(b.id));
        font.otherChars = chars;
    }

    private static Texture2D Sheet() {
        var bytes = RandomizerResources.ReadResource(Art);
        if (bytes == null) {
            return null;
        }

        var sheet = new Texture2D(0, 0);
        sheet.LoadImage(bytes);
        return sheet;
    }

    private static TextBoxIconsFontGenerator Font() {
        foreach (var renderer in Resources.FindObjectsOfTypeAll<MoonIconRenderer>()) {
            if (renderer != null && renderer.Icons != null) {
                return renderer.Icons;
            }
        }

        return null;
    }

    private static Transform Parked() {
        if (parked == null) {
            var holder = new GameObject("randomizerKeyCaps");
            UnityEngine.Object.DontDestroyOnLoad(holder);
            holder.SetActive(false);
            parked = holder.transform;
        }

        return parked;
    }

    private const string Art = "key_caps.png";

    // the font's Enter, the cap ours sit beside most; the game's caps are not all one size
    private const char Sized = 'D';

    private const float Fits = 0.88f;

    // the strength the game's own caps are drawn at
    private const float Softened = 0.45f;

    // advance added to every cap, matching the game's own spacing
    private const float Margin = 0.2f;

    // widths of the two blanks: Pad parts two hints, Clearance clears a held key's ring
    private const float Pad = 1.1f;

    private const float Clearance = 0.32f;

    // Backspace's Cap.Trim
    private const float Wide = 0.37f;

    // solid enough to be the cap rather than the glow around it
    private const byte Faint = 128;

    // alpha gain for the cap's solid pixels (Firm) and for its glow (Halo)
    private const float Firm = 1.9f;

    private const float Halo = 0.45f;

    // darker than this is plate, not border or lettering; Dim..Lit is the light across it
    private const int Plate = 60;

    private const int Dim = 5;

    private const int Lit = 68;

    // how much of the fade is vertical rather than horizontal, and how much tooth it has
    private const float Rise = 0.62f;

    private const float Grit = 16f;

    // start of the Unicode private use area
    private const int Private = 0xE000;

    private static readonly Dictionary<KeyCode, Cap> keys = new Dictionary<KeyCode, Cap>();

    private static readonly List<BitmapFont> widened = new List<BitmapFont>();

    private static bool registered;

    private static bool registering;

    private static bool failed;

    private static Transform parked;

    private static readonly char[] blanks = new char[2];

    private static string gap = string.Empty;

    private static string thin = string.Empty;
}
